model_list:
  - model_name: gpt-5-mini
    litellm_params:
      model: azure/gpt-5-mini
      api_base: https://<your-azure-here>.openai.azure.com
      api_key: os.environ/AZURE_API_KEY
      api_version: "v1"
router_settings:
  optional_pre_call_checks: ["responses_api_deployment_check"]
